sudo: required
services:
  - docker

before_install:
  - docker build -t numery/docker-react -f Dockerfile.dev .

script:
#  - docker run numery/docker-react npm run test -- --coverage
  - docker run -e CI=true numery/docker-react npm run test